routes/web.php
<?php

use App\Http\Controllers\CartController;
use App\Http\Controllers\CommentController;
use App\Http\Controllers\FrontendController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\CategoryController;
use App\Mail\OrderCreated;
use App\Models\Product;
use App\Models\Category;
use App\Models\User;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('send-mail', function(){

    $user = User::first();
    $product = Product::first();

    \Mail::to('mdahosanhabib@outlook.com')->send(
        new OrderCreated($user, $product)
    );
});

Route::get('products/{product}', [FrontendController::class, 'show'])->name('single-product');
Route::post('products/{product}/comment', [CommentController::class, 'store'])->name('product-comment');
Route::post('products/{product}/add-to-cart', [CartController::class, 'store'])->name('update-cart');
Route::get('/shoping-bag', [CartController::class, 'shopingBag'])->name('shoping-bag');
Route::post('/orders/create', [OrderController::class, 'store'])->name('orders.create');
Route::get('/orders/success', [OrderController::class, 'success'])->name('orders.success');

// Update: PUT/PATCH
// Delete: DELETE

Route::prefix('admin')->middleware('auth')->group(function () {
   
    Route::get('/deleted-products', [ProductController::class, 'trash'])->name('products.trash');
    Route::get('/deleted-products/{id}/restore', [ProductController::class, 'restore'])->name('products.restore');
    Route::delete('/deleted-products/{id}', [ProductController::class, 'delete'])->name('products.delete');
    Route::get('/products/download-pdf', [ProductController::class, 'pdf'])->name('products.pdf');

    Route::get('/deleted-categories', [CategoryController::class, 'trash'])->name('categories.trash');
    Route::get('/deleted-categories/{id}/restore', [CategoryController::class, 'restore'])->name('categories.restore');
    Route::delete('/deleted-categories/{id}', [CategoryController::class, 'delete'])->name('categories.delete');
    Route::get('/categories/download-pdf', [CategoryController::class, 'pdf'])->name('categories.pdf');


    // Route::get('/products', [ProductController::class, 'index'])->name('products.index');
    // Route::get('/products/create', [ProductController::class, 'create'])->name('products.create');
    // Route::post('/products/store', [ProductController::class, 'store'])->name('products.store');
    // Route::get('/products/{product}', [ProductController::class, 'show'])->name('products.show');
    // Route::get('/products/{product}/edit', [ProductController::class, 'edit'])->name('products.edit');
    // Route::patch('/products/{product}', [ProductController::class, 'update'])->name('products.update');
    // Route::delete('/products/{product}', [ProductController::class, 'destroy'])->name('products.destroy');

    Route::resource('products', ProductController::class);
    Route::resource('categories', CategoryController::class);

    Route::get('my-profile', function(){
        dd(auth()->user()->profile);
    })->name('my-profile');

});

require __DIR__.'/auth.php';

// Route::get('/dashboard', function () {
//     return view('dashboard');
// })->middleware(['auth'])->name('dashboard');


Route::get('/dashboard', function () {
    return view('backend.dashboard');
})->middleware('checkAgeMiddleware');

Route::get('/categories/{categoryId?}', [FrontendController::class, 'welcome'])->name('category-wise-product');

Route::get('/', [FrontendController::class, 'welcome'])->name('welcome');

Route::get('/table', function () {
    return view('backend.table');
});

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use HasFactory;

    protected $fillable = ['title', 'description'];

    public function products()
    {
        return $this->hasMany(Product::class);
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CategoryRequest;
use App\Models\Category;
use Illuminate\Http\Request;
use App\Models\Tag;
use GuzzleHttp\Psr7\Query;
use Illuminate\Database\QueryException;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Session;
use Image;
use PDF;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // $categories = Category::all();
        $categories = Category::orderBy('id', 'desc')->get();
        return view('backend.categories.index', compact('categories'));
    }

    public function create()
    {
        $categories = Category::pluck('title', 'id')->toArray();
        $tags = Tag::pluck('title', 'id')->toArray();
        return view('backend.categories.create', compact('categories', 'tags'));
    }

    public function store(CategoryRequest $request)
    {
        try {
            $requestData = $request->all();

            // $requestData['created_by'] = auth()->user()->id;
            $category = Category::create($requestData);
          
            // Session::flush('message', 'Successfully Saved');
            // return redirect()->route('categories.index')->with('message','Successfully Saved !');
            return redirect()->route('categories.index')->withMessage('Successfully Saved !');
        } catch (QueryException $e) {
            return redirect()->back()->withInput()->withErrors($e->getMessage());
        }
    }

    public function show(Category $category) //dependency injection
    {
        $this->authorize('category-show', $category);
        // $category = Category::where('id', $id)->first();
        // $category = Category::where('id', $id)->firstOrFail();

        // $category = Category::findOrFail($category);

        // return view('backend.categories.show', [
        //     'category' => $category
        // ]);

        return view('backend.categories.show', compact('category'));
    }

    public function edit(Category $category)
    {
        $this->authorize('category-edit', $category);

        $categories = Category::pluck('title', 'id')->toArray();
        // $category = Category::findOrFail($id);
        return view('backend.categories.edit', compact('category', 'categories'));
    }

    public function update(Request $request, Category $category)
    {
        try {
            $requestData = $request->all();

            // $category = Category::findOrFail($id);

            if ($request->hasFile('image')) {
                $file = $request->file('image');
                $fileName = time() . '.' . $file->getClientOriginalExtension();
                Image::make($request->file('image'))
                    ->resize(300, 200)
                    ->save(storage_path() . '/app/public/categories/' . $fileName);
                $requestData['image'] = $fileName;
            } else {
                $requestData['image'] = $category->image;
            }

            $requestData['updated_by'] = auth()->id();
            $category->update($requestData);

            return redirect()->route('categories.index')->withMessage('Successfully Updated !');
        } catch (QueryException $e) {
            return redirect()->back()->withInput()->withErrors($e->getMessage());
        }
    }

    public function destroy(Category $category)
    {
        $this->authorize('category-delete', $category);
        // $category = Category::findOrFail($id);
        $category->update(['deleted_by'=>auth()->id()]);

        $category->delete();

        return redirect()->route('categories.index')->withMessage('Successfully Deleted !');
    }

    public function trash()
    {
        $this->authorize('category-trash-list');

        $categories = Category::onlyTrashed()->get();
        return view('backend.categories.trash', compact('categories'));
    }

    public function restore($id)
    {
        Category::withTrashed()
            ->where('id', $id)
            ->restore();

        return redirect()->route('categories.trash')->withMessage('Successfully Restored !');
    }

    public function delete($id)
    {
        Category::withTrashed()
            ->where('id', $id)
            ->forceDelete();

        return redirect()->route('categories.trash')->withMessage('Deleted Successfully');
    }

    public function pdf()
    {
        $categories = Category::latest()->get();
        $pdf = PDF::loadView('backend.categories.pdf', compact('categories'));
        return $pdf->download('categories.pdf');
    }
}

resources/views/backend/categories/create.blade.php
<x-backend.layouts.master>
    <h1 class="mt-4">Categories</h1>
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item"><a href="index.html">Dashboard</a></li>
        <li class="breadcrumb-item active">categories</li>
    </ol>

    <div class="card mb-4">
        <div class="card-header">
            <i class="fas fa-table me-1"></i>
            Category Create
            <a class="btn btn-sm btn-primary" href="{{ route('categories.index') }}">List</a>
        </div>
        <div class="card-body">

            @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
            @endif

            <form action="{{ route('categories.store') }}" method="POST" enctype="multipart/form-data">
                @csrf

                <div class="mb-3">
                   
                    @error('category_id')
                        <div class="text-danger">{{ $message }}</div>
                    @enderror
                </div>

                <div class="mb-3">
                    <label for="title" class="form-label">Title</label>
                    <input name="title" type="text" class="form-control" id="title" value="{{ old('title') }}">

                    @error('title')
                    <div class="text-danger">{{ $message }}</div>
                    @enderror
                </div>

               

                <div class="mb-3">
                    <label for="description" class="form-label">Description</label>
                    <textarea name="description" class="form-control" rows="10" id="description">
                        {{ old('description') }}
                    </textarea>
                    @error('description')
                    <div class="text-danger">{{ $message }}</div>
                    @enderror
                </div>

                

                @foreach ($tags as $key=>$tag)
                    <input id="{{$key}}" type="checkbox" name="tag_ids[]" value="{{$key}}"/>
                    <label for="{{$key}}">{{ $tag }}</label><br>
                @endforeach

                <button type="submit" class="btn btn-primary">Save</button>
            </form>
        </div>
    </div>
</x-backend.layouts.master>

resources/views/backend/categories/edit.blade.php
<x-backend.layouts.master>
    <h1 class="mt-4">Categories</h1>
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item"><a href="index.html">Dashboard</a></li>
        <li class="breadcrumb-item active">categories</li>
    </ol>

    <div class="card mb-4">
        <div class="card-header">
            <i class="fas fa-table me-1"></i>
            Category Edit
            <a class="btn btn-sm btn-primary" href="{{ route('categories.index') }}">List</a>
        </div>
        <div class="card-body">

            @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
            @endif

            <form action="{{ route('categories.update', ['category' => $category->id]) }}" method="POST" enctype="multipart/form-data">

                @csrf
                @method('PATCH')


                <div class="mb-3">
                    <label for="category_id" class="form-label">Category</label>
                    <select name="category_id" id="category_id" class="form-control">
                        <option value="">Select One</option>
                        @foreach ($categories as $key=>$category)
                        <option value="{{$key}}" {{ $category->category_id == $key ? 'selected' : '' }}>{{$category}}</option>
                        @endforeach
                    </select>
                    @error('category_id')
                    <div class="text-danger">{{ $message }}</div>
                    @enderror
                </div>

                <div class="mb-3">
                    <label for="title" class="form-label">Title</label>
                    <input name="title" type="text" class="form-control" id="title" value="{{ old('title', $category->title) }}">

                    @error('title')
                    <div class="text-danger">{{ $message }}</div>
                    @enderror
                </div>

                <div class="mb-3">
                    <label for="price" class="form-label">Price</label>
                    <input name="price" type="number" class="form-control" id="price" value="{{ old('price', $category->price) }}">
                    @error('price')
                    <div class="text-danger">{{ $message }}</div>
                    @enderror
                </div>

                <div class="mb-3">
                    <label for="description" class="form-label">Description</label>
                    <textarea name="description" class="form-control" rows="10" id="description">
                    {{ old('description', $category->description) }}
                    </textarea>
                    @error('description')
                    <div class="text-danger">{{ $message }}</div>
                    @enderror
                </div>

                <div class="mb-3">
                    <label for="image" class="form-label">Image</label>
                    <input name="image" type="file" class="form-control" id="image">
                    @error('image')
                    <div class="text-danger">{{ $message }}</div>
                    @enderror
                </div>

                <button type="submit" class="btn btn-primary">Save</button>
            </form>
        </div>
    </div>


    <script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>

    <script>
        tinymce.init({
            selector: 'textarea#description',
            height: 500,
            menubar: false,
            plugins: [
                'advlist autolink lists link image charmap print preview anchor',
                'searchreplace visualblocks code fullscreen',
                'insertdatetime media table paste code help wordcount'
            ],
            toolbar: 'undo redo | formatselect | ' +
                'bold italic backcolor | alignleft aligncenter ' +
                'alignright alignjustify | bullist numlist outdent indent | ' +
                'removeformat | help',
            content_style: 'body { font-family:Helvetica,Arial,sans-serif; font-size:14px }'
        });
    </script>




</x-backend.layouts.master>

resources/views/backend/categories/index.blade.php
<x-backend.layouts.master>
    <h1 class="mt-4">Categories</h1>
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item"><a href="index.html">Dashboard</a></li>
        <li class="breadcrumb-item active">categories</li>
    </ol>

    <div class="card mb-4">
        <div class="card-header">
            <i class="fas fa-table me-1"></i>
            Category List

            <!-- <a class="btn btn-sm btn-info" href="{{ route('categories.pdf') }}">PDF</a>
            @can('category-trash-list')
            <a class="btn btn-sm btn-info" href="{{ route('categories.trash') }}">Trash List</a>
            @endcan -->
            <a class="btn btn-sm btn-primary" href="{{ route('categories.create') }}">Add New</a>
        </div>
        <div class="card-body">

            @if(session('message'))
            <p class="alert alert-success">{{ session('message') }}</p>
            @endif

            <table id="datatablesSimple">
                <thead>
                    <tr>
                        <th>SL</th>
                        <th>Title</th>
                        <th>Description</th>
                        <th>Action</th>
                    </tr>
                </thead>

                <tbody>

                    @foreach ($categories as $category)
                    <tr>
                        <td>{{ $loop->iteration }}</td>
                        <td>{{ $category->title }}</td>
                        
                        <td>{{ $category->category->description ?? 'N/A' }}</td>
                        <td>

                            @can('category-show', $category)
                            <a class="btn btn-info btn-sm" href="{{ route('categories.show', ['category' => $category->id]) }}">Show</a>    
                            @endcan

                            @can('category-edit', $category)
                            <a class="btn btn-warning btn-sm" href="{{ route('categories.edit', ['category' => $category->id]) }}">Edit</a>    
                            @endcan
                            
                            @can('category-delete', $category)
                            <form action="{{ route('categories.destroy', ['category' => $category->id]) }}" method="POST" 
                                style="display:inline">
                                @csrf
                                @method('delete')
                                <button type="submit" class="btn btn-danger btn-sm" onclick="return confirm('Are you sure want to delete ?')">Delete</button>
                            </form>
                            @endcan

                        </td>
                    </tr>
                    @endforeach

                </tbody>
            </table>
        </div>
    </div>
</x-backend.layouts.master>

resources/views/backend/categories/pdf.blade.php
<table border="1" style="width: 700px;">
    <tr>
        <th>Sl#</th>
        <th>Name</th>
        <th>Price</th>
    </tr>
    @foreach ($categories as $category)
    <tr>
        <td>{{ $loop->iteration }}</td>
        <td>{{ $category->title }}</td>
        <td>{{ $category->price }} BDT</td>
    </tr>
    @endforeach
</table>

resources/views/backend/categories/show.blade.php
<x-backend.layouts.master>
    <h1 class="mt-4">categories</h1>
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item"><a href="index.html">Dashboard</a></li>
        <li class="breadcrumb-item active">Categories</li>
    </ol>

    <div class="card mb-4">
        <div class="card-header">
            <i class="fas fa-table me-1"></i>
            Category Details
            <a class="btn btn-sm btn-primary" href="{{ route('categories.index') }}">List</a>
        </div>
        <div class="card-body">
            <h3>Category: {{ $category->category->title ?? 'N/A' }}</h3>
            <h3>Title: {{ $category->title }}</h3>
            <p>Description: {{ $category->description }}</p>
            <p>Price: {{ $category->price }}</p>
            <img src="{{ asset('storage/categories/'. $category->image) }}" />
            <p>Created At: {{ $category->created_at->diffForHumans() }} By: {{$category->createdBy->name??'N/A'}}</p>
            <p>Updated At: {{ $category->updated_at->diffForHumans() }} By: {{$category->updatedBy->name??'N/A'}}</p>
        </div>

    </div>
</x-backend.layouts.master>

resources/views/backend/categories/trash.blade.php
<x-backend.layouts.master>
    <h1 class="mt-4">Categories</h1>
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item"><a href="index.html">Dashboard</a></li>
        <li class="breadcrumb-item active">Deleted categories</li>
    </ol>

    <div class="card mb-4">
        <div class="card-header">
            <i class="fas fa-table me-1"></i>
            Deleted Category List
            <a class="btn btn-sm btn-primary" href="{{ route('categories.index') }}">List</a>
        </div>
        <div class="card-body">

            @if(session('message'))
            <p class="alert alert-success">{{ session('message') }}</p>
            @endif

            <table id="datatablesSimple">
                <thead>
                    <tr>
                        <th>SL</th>
                        <th>Title</th>
                        <th>Price</th>
                        <th>Action</th>
                    </tr>
                </thead>

                <tbody>

                    @foreach ($categories as $category)
                    <tr>
                        <td>{{ $loop->iteration }}</td>
                        <td>{{ $category->title }}</td>
                        <td>{{ $category->price }} TK</td>
                        <td>

                            <a class="btn btn-warning btn-sm" href="{{ route('categories.restore', ['id' => $category->id]) }}">Restore</a>

                            <form action="{{ route('categories.delete', ['id' => $category->id]) }}" method="POST" 
                                style="display:inline">
                                @csrf
                                @method('delete')
                                <button type="submit" class="btn btn-danger btn-sm" onclick="return confirm('Are you sure want to delete ?')">Delete</button>
                            </form>

                        </td>
                    </tr>
                    @endforeach

                </tbody>
            </table>
        </div>
    </div>
</x-backend.layouts.master>